src/Entity/Game.php
<?php

namespace App\Entity;

use App\Repository\GameRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: GameRepository::class)]
class Game
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(type: 'string')]
    private string $picture;

    #[ORM\Column]
    private ?int $players = null;

    #[ORM\Column(length: 100)]
    private ?string $age = null;

    #[ORM\Column(length: 100)]
    private ?string $time = null;

    #[ORM\Column(length: 255)]
    private ?string $link = null;

    #[ORM\ManyToMany(targetEntity: Category::class, inversedBy: 'games')]
    private Collection $category;

    #[ORM\ManyToOne(inversedBy: 'games')]
    private ?User $user = null;

    #[ORM\OneToMany(mappedBy: 'game', targetEntity: Loan::class)]
    private Collection $loans;

    public function __construct()
    {
        $this->category = new ArrayCollection();
        $this->loans = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getPlayers(): ?int
    {
        return $this->players;
    }

    public function setPlayers(int $players): static
    {
        $this->players = $players;

        return $this;
    }

    public function getAge(): ?string
    {
        return $this->age;
    }

    public function setAge(string $age): static
    {
        $this->age = $age;

        return $this;
    }

    public function getTime(): ?string
    {
        return $this->time;
    }

    public function setTime(string $time): static
    {
        $this->time = $time;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(string $link): static
    {
        $this->link = $link;

        return $this;
    }

    /**
     * @return Collection<int, Category>
     */
    public function getCategory(): Collection
    {
        return $this->category;
    }

    public function addCategory(Category $category): static
    {
        if (!$this->category->contains($category)) {
            $this->category->add($category);
        }

        return $this;
    }

    public function removeCategory(Category $category): static
    {
        $this->category->removeElement($category);

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Loan>
     */
    public function getLoans(): Collection
    {
        return $this->loans;
    }

    public function addLoan(Loan $loan): static
    {
        if (!$this->loans->contains($loan)) {
            $this->loans->add($loan);
            $loan->setGame($this);
        }

        return $this;
    }

    public function removeLoan(Loan $loan): static
    {
        if ($this->loans->removeElement($loan)) {
            // set the owning side to null (unless already changed)
            if ($loan->getGame() === $this) {
                $loan->setGame(null);
            }
        }

        return $this;
    }
}

src/Entity/Loan.php
<?php

namespace App\Entity;
use Symfony\Component\Validator\Constraints as Assert;
use App\Repository\LoanRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LoanRepository::class)]
class Loan
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Assert\Range(
        min: 'first day of January',
        max: 'first day of January next year',
    )]
    #[Assert\GreaterThan('today')]
    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_start = null;
    
    #[Assert\GreaterThan(propertyPath: 'date_start')]
    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_end = null;

    #[ORM\ManyToOne(inversedBy: 'loans')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Game $game = null;

    #[ORM\ManyToOne(inversedBy: 'loans')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->date_start;
    }

    public function setDateStart(\DateTimeInterface $date_start): static
    {
        $this->date_start = $date_start;

        return $this;
    }

    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->date_end;
    }

    public function setDateEnd(\DateTimeInterface $date_end): static
    {
        $this->date_end = $date_end;

        return $this;
    }

    public function getGame(): ?Game
    {
        return $this->game;
    }

    public function setGame(?Game $game): static
    {
        $this->game = $game;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/GameType.php
<?php

namespace App\Form;

use App\Entity\Game;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class GameType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('content')
            ->add('description')
            ->add('date', DateType::class, [
                'years' => range(date('Y') - 43, date('Y')), 
            ])
            ->add('picture', FileType::class, ['mapped'=>false,'required'=>false])
            ->add('players')
            ->add('age')
            ->add('time')
            ->add('link')
            ->add('category')
            ->add('save', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Game::class,
        ]);
    }
}

src/Controller/GameController.php
<?php

namespace App\Controller;

use App\Entity\Game;
use App\Entity\Category;
use App\Form\GameType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\String\Slugger\SluggerInterface; 
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\File;

class GameController extends AbstractController
{
    #[Route('/game', name: 'app_game')]
    public function index(EntityManagerInterface $em): Response
    {
        $games = $em->getRepository(Game::class);
        $game = $games->findAll();
        $categories = $em->getRepository(Category::class);
        $category = $categories->findAll();

        return $this->render('game/index.html.twig', [
            'games' => $game,
            'categories' => $category,
        ]);

    }

    #[Route('/game/new', name: 'app_game_new')]

    public function addGame(Request $request, EntityManagerInterface $em, SluggerInterface $slugger): Response
    {
        $game = new Game();
        $categories = $em->getRepository(Category::class);
        $category = $categories->findAll();
        $form = $this->createForm(GameType::class, $game);
        $form-> handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                /** @var UploadedFile $brochureFile */
                $pictureFile = $form->get('picture')->getData();

                // this condition is needed because the 'brochure' field is not required
                // so the PDF file must be processed only when a file is uploaded
                if ($pictureFile) {
                    $originalFilename = pathinfo($pictureFile->getClientOriginalName(), PATHINFO_FILENAME);
                    // this is needed to safely include the file name as part of the URL
                    $safeFilename = $slugger->slug($originalFilename);
                    $newFilename = $safeFilename.'-'.uniqid().'.'.$pictureFile->guessExtension();
    
                    // Move the file to the directory where brochures are stored
                    try {
                        $pictureFile->move(
                            $this->getParameter('brochures_directory'),
                            $newFilename
                        );
                    } catch (FileException $e) {
                        echo "image echoué";
                    }
    
                    // updates the 'brochureFilename' property to store the PDF file name
                    // instead of its contents
                    
                    $game = $form->getData();
                    $game->setPicture($newFilename);
                    $game->setUser($this->getUser());
                    $em->persist($game);
                    $em->flush();
                    return $this->redirectToRoute('app_game');
                }
            }
            return $this->render('game/new.html.twig', [
                'form' => $form,
                'categories' => $category,
            ]);   
   }

   #[Route('/game/{id}', name:'app_game_show')]
    public function show(EntityManagerInterface $em, int $id) : Response
    {
        $games = $em->getRepository(Game::class);
        $game = $games->find($id);
        $categories = $em->getRepository(Category::class);
        $category = $categories->findAll();
        return $this->render('game/show.html.twig', [
            'game' => $game,
            'categories' => $category,

        ]);
    }

    #[Route('/game/edit/{id}', name:'app_game_edit')]
    public function update(Request $request, EntityManagerInterface $em,  int $id , SluggerInterface $slugger): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        $games = $em->getRepository(Game::class) ;
        $game = $games->find($id);
        $categories = $em->getRepository(Category::class);
        $category = $categories->findAll();
        $form = $this->createForm(GameType::class, $game);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
             /** @var UploadedFile $brochureFile */
             $pictureFile = $form->get('picture')->getData();

             // this condition is needed because the 'brochure' field is not required
             // so the PDF file must be processed only when a file is uploaded
            if ($pictureFile) {
                 $originalFilename = pathinfo($pictureFile->getClientOriginalName(), PATHINFO_FILENAME);
                 // this is needed to safely include the file name as part of the URL
                 $safeFilename = $slugger->slug($originalFilename);
                 $newFilename = $safeFilename.'-'.uniqid().'.'.$pictureFile->guessExtension();
 
                 // Move the file to the directory where brochures are stored
                 try {
                    
                     $pictureFile->move(
                         $this->getParameter('brochures_directory'),
                         $newFilename
                     );
                     $game->setPicture($newFilename);

                 } catch (FileException $e) {
                     echo "image echoué";
                 }
 
                 // updates the 'brochureFilename' property to store the PDF file name
                 // instead of its contents
                
            }
            
            $em->flush();
            return $this->redirectToRoute('app_game');
        }
        return $this->render('game/edit.html.twig', [
            'form' => $form,
            'categories' => $category,
        ]);   
   }

   #[Route('game/delete/{id}', name: 'app_game_delete')]
   public function delete(EntityManagerInterface $em, int $id): Response
   {
    $games = $em->getRepository(Game::class);
    $game = $games->find($id);
    $file = 'Uploads/' . $game->getPicture();
   if( file_exists($file)){
        unlink($file);
    }
    $em->remove($game);
    $em->flush();
    
    return $this->redirectToRoute('app_game');
   }
} 

templates/game/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification{% endblock %}

{% block body %}
 
    
    {% if is_granted('ROLE_USER') %}
     <a href="/game/" type="button" class="btn btn-primary m-2">Retour</a>
     <h1 class="text-center"> Modifier le jeu déposer </h1>
      <article class="container">
         {{ form(form) }}
    

         {# <div class="alert alert-primary d-flex align-items-center" role="alert">
            <svg xmlns="http://www.w3.org/2000/svg" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
             <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
            </svg>
         <div>
             An example alert with an icon
          </div>
         </div> #}
      </article>
    {% endif %}

{% endblock %}

templates/game/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello GameController!{% endblock %}

{% block body %}
    <h1>
        Liste des jeux
    </h1>
    <div class='container'>
      {% for game in games %}
        <div class="card" style="width: 18rem;">
          <img src="Uploads/{{ game.picture }}">
            <div class="card-body">
              <h5 class="card-title">{{ game.name }}</h5>
              <h5 class="card-title">id user : {{ game.id }}</h5>
              <p class="card-text">{{ game.date | format_date(locale='fr') }}</p>
              <p class="card-text"> {{ game.players }}</p>
              <p class="card-text">{{ game.age }}</p>
              <p class="card-text">{{ game.time }}</p>
              <p class="card-text">{{ game.link }}</p>
              {% for categorie in game.category %}
              <p class="card-text">{{ categorie }}</p>
              {% endfor %}
             <a href="/game/{{game.id}}" type="button" class="btn btn-primary">Détails</a><br>
            </div>
        </div>
      {% endfor %}
    </div>
{% endblock %}

templates/game/new.html.twig
{% extends 'base.html.twig' %}

{% block title %} New Form Game {% endblock %}

{% block body %}

    <h1>
        Ajouter un jeu de société
    </h1>
    <article class="container">
        {{ form(form) }}
    </article>

{% endblock %}




{# <form class="row g-3">
  <div class="col-md-4">
    <label for="validationDefault01" class="form-label">First name</label>
    <input type="text" class="form-control" id="validationDefault01" value="Mark" required>
  </div>
  <div class="col-md-4">
    <label for="validationDefault02" class="form-label">Last name</label>
    <input type="text" class="form-control" id="validationDefault02" value="Otto" required>
  </div>
  <div class="col-md-4">
    <label for="validationDefaultUsername" class="form-label">Username</label>
    <div class="input-group">
      <span class="input-group-text" id="inputGroupPrepend2">@</span>
      <input type="text" class="form-control" id="validationDefaultUsername" aria-describedby="inputGroupPrepend2" required>
    </div>
  </div>
  <div class="col-md-6">
    <label for="validationDefault03" class="form-label">City</label>
    <input type="text" class="form-control" id="validationDefault03" required>
  </div>
  <div class="col-md-3">
    <label for="validationDefault04" class="form-label">State</label>
    <select class="form-select" id="validationDefault04" required>
      <option selected disabled value="">Choose...</option>
      <option>...</option>
    </select>
  </div>
  <div class="col-md-3">
    <label for="validationDefault05" class="form-label">Zip</label>
    <input type="text" class="form-control" id="validationDefault05" required>
  </div>
  <div class="col-12">
    <div class="form-check">
      <input class="form-check-input" type="checkbox" value="" id="invalidCheck2" required>
      <label class="form-check-label" for="invalidCheck2">
        Agree to terms and conditions
      </label>
    </div>
  </div>
  <div class="col-12">
    <button class="btn btn-primary" type="submit">Submit form</button>
  </div>
</form> #}

templates/game/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détails du bien{% endblock %}

{% block body %}
  <h1 class="text-center">Détails du jeu</h1>
  <article class="container">
      <div class="card text-center mt-5">
        <div class="card-header">
          Location
        </div>
        <div class="card-body">
          <h5 class="card-title">{{ game.name }}</h5>
              <h5 class="card-title">id user : {{ game.id }}</h5>
          <h5 class="card-title"> Type : {{ game.content }}</h5>
          <address class="card-text">{{ game.description }}</address>
          <p class="card-text">{{ game.date | format_date(locale='fr') }}</p>
          <img class='w-2 h-2' src="/Uploads/{{ game.picture }}">
          <p> {{game.players}}</p> 
          <p> {{game.age}}</p>  
          <p> {{game.time}}</p>  
          <p> {{game.link}}</p> 
          {% for categorie in game.category %}
              <p class="card-text">{{ categorie }}</p>
          {% endfor %} 
          {% for loan in game.loans %}
              <p class="card-text">ce jeu est loué du : {{ loan.dateStart | format_date(locale='fr') }} au {{ loan.dateEnd | format_date(locale='fr') }}</p>
          {% endfor %} 
        </div>
         <a href="/game/" type="button" class="btn btn-primary mt-1">Retour</a>
        {% if is_granted('ROLE_USER')%}
        <div>
        {% if game.user == app.user %}
         <a href="/game/edit/{{game.id}}" type="button" class="btn btn-primary mt-1">Modifier</a>
         <a href="/game/delete/{{game.id}}" type="button" class="btn btn-primary mt-1">Supprimer</a>
         {% endif %}
         <a href="/loan/{{game.id}}" type="button" class="btn btn-primary mt-1">Louer</a>
        </div>
        {% else %}
        <span>Vous devez être connecté pour loué un jeu</span>
        {% endif %}
        
  </article>      
{% endblock %}